version: "3.9"
services:
  fproject.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
      - "5001:443"
    secrets:
      - source: cert.pfx
        target: /app/cert.pfx
        mode: 0400
      - source: appsettings.Production.json
        target: /app/appsettings.Production.json
        mode: 0400
secrets:
  cert.pfx:
    file: FProject/Server/cert.pfx
  appsettings.Production.json:
    file: FProject/Server/appsettings.Production.json
